services:
  user:
    build: ./user-service
    ports:
      - "4002:4002"

  admin:
    build: ./admin-service
    ports:
      - "4000:4000"

  auth:
    build: ./oauth-service
    ports:
      - "4001:4001"

  order:
    build: ./order-service
    ports:
      - "4004:4004"
    environment:
      API_USER: "http://user:4002/api/user/order"
      API_DETAIL: "http://user:4002/api/detail/order"
      API_CART: "http://cart:4003/api/cart/order"
      API_PRODUCT: "http://admin:4000/api/product"
      API_ADMIN: "http://admin:4000/api/admin"

  payment:
    build: ./payment-service
    ports:
      - "4008:4008"
    environment:
      API_ORDER: "http://order:4004/api/order"

  cart:
    build: ./cart-service
    ports:
      - "4003:4003"
    environment:
      API_PRODUCT: "http://admin:4000/api/product"