services:
  user:
    build: ./USER-SERVICE
    ports:
      - "4002:4002"

  admin:
    build: ./ADMIN-SERVICE
    ports:
      - "4000:4000"

  auth:
    build: ./OAUTH-SERVICE
    ports:
      - "4001:4001"

  order:
    build: ./ORDER-SERVICE
    ports:
      - "4004:4004"
    environment:
      API_USER: "http://user:4002/api/user/order"
      API_USERDETAIL: "http://user:4002/api/userdetail"
      API_CART: "http://cart:4003/api/cart/order"
      API_PRODUCT: "http://admin:4000/api/product"
      API_ADMIN: "http://admin:4000/api/admin"

  cart:
    build: ./CART-SERVICE
    ports:
      - "4003:4003"
    environment:
      API_PRODUCT: "http://admin:4000/api/product"