export const ORDER_STATUS = Object.freeze({
  NEW: "NEW",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PROCESSING: "PROCESSING",
  PAID: "PAID",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
});
